
Neos:
  Demo:
    flickr:
      tagStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&tags=%s'
      userStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&id=%s'
  Form:
    yamlPersistenceManager:
      savePath: 'resource://Neos.Demo/Private/Form/'
    presets:
      bootstrap:
        title: 'Twitter bootstrap'
        parentPreset: default
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Neos.Demo/Private/Templates/ContactForm/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: form-control
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: print
          title: 'Neos.Demo:Main:editPreviewModes.print'
          position: 200
      translation:
        autoInclude:
          Neos.Demo:
            - Main
            - 'NodeTypes/*'
  ContentRepository:
    contentDimensions:
      language:
        label: 'Neos.Demo:Main:contentDimensions.language'
        icon: icon-language
        default: en_US
        defaultPreset: en_US
        presets:
          all: null
          en_US:
            label: 'English (US)'
            values:
              - en_US
            uriSegment: en
          en_UK:
            label: 'English (UK)'
            values:
              - en_UK
              - en_US
            uriSegment: uk
          de:
            label: German
            values:
              - de
            uriSegment: de
          fr:
            label: French
            values:
              - fr
            uriSegment: fr
          nl:
            label: Dutch
            values:
              - nl
              - de
            uriSegment: nl
          da:
            label: Danish
            values:
              - da
            uriSegment: da
          lv:
            label: Latvian
            values:
              - lv
            uriSegment: lv
